mybatis:
  mapper-locations: classpath:mybatis/*.xml
server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 3
    maxActive: 10
    maxWait: 50000
    minIdle: 10
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filter:
        stat:
          db-type: mysql
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 2000
        wall:
          config:
            delete-row: false
            drop-table-allow: false
          db-type: mysql
          enabled: true


  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  thymeleaf:
    prefix: classpath:/templates/
  cache:
    type: ehcache
    ehcache:
      config: classpath:/ehcache.xml
  quartz:
    job-store-type: memory
    auto-startup: true
#    properties:
#      org:
#        quartz:
#          jobStore:
#            isClustered: true
#            clusterCheckinInterval: 20000
#            dataSource: myDS
#            class: org.quartz.impl.jdbcjobstore.JobStoreTX
#            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
#            tablePrefix: QRTZ_
#          threadPool:
#            class: org.quartz.simpl.SimpleThreadPool
#            threadCount: 25
#            threadPriority: 5
#          scheduler:
#            instanceId: AUTO
#            instanceName : MyClusteredScheduler
#          dataSource:
#            myDS:
#              URL: jdbc:mysql://192.168.4.251:3306/qtz?useUnicode=true&characterEncoding=utf8&useTimezone=true&serverTimezone=GMT%2B8
#              driver: com.mysql.jdbc.Driver
#              maxConnections: 5
#              password: root
#              user: root@db.251
#              validationQuery: select 0 from dual
